### PR TITLE
More columnizer

### PR DESCRIPTION
**Pull request by miltob**

### CODE REVIEW

**Comment by miltob** [comment]
@zarunbal There are some changes that I have done here.

1. Added an AutoColumnizer. In the future, I am thinking about add a "priority" field and a "DoesFit" method in ILogLineColumnizer interface so all columnizer can be loaded automatically.
2. Modified JsonColumnizer for better compatibility.
3. Added two new columnizers.

Please take a look and let me know your opinion. I'd like to make changes gradually. I'll try make smaller but frequent ones in the future.
P.S. I think the master is a bit behind and there are some good features are not in formal releases. Maybe we could release more often so that other people enjoy the latest changes.

**Comment by miltob** [comment]
Supported Priority for AutoColumnizer.
When open a file, the AutoColumnizer should be able to find the most relevant columnizer for most of the case.

**Comment by zarunbal** [comment]
Thank you @miltob for this new columnizer. I have currently a bit trouble with my PC and limited access to VS. I try as fast as possible to review and merge this.

**Comment by zarunbal** [comment]
Thanks again for the PR and I would appreciate gradually changes.

**Pull request merged**
