### PR TITLE
Use date format from regional settings

### PR DESCRIPTION
**Pull request by igitur**
Implements simple date time format parser to break up the date format into its parts and implement it in the `DateTimeDragControl`.

### CODE REVIEW

**Comment by igitur** [comment]
Let me know if I should explain in more detail what this PR, and the date format parser does.

**Comment by zarunbal** [comment]
Thanks for adapting / updating your PR to the changes. I'll have a look into it soon (Hopefully that I have some more free time). I currently try to finish the Release pipeline so I have less work to release a new version.

**Comment by zarunbal** [comment]
Again thanks for your contribution! It would be great if you could add some unit tests at least for the non gui parts, by time.

**Comment by igitur** [comment]
Sure, I'll add unit tests later.

**Pull request merged**
