### PR TITLE
Update Versions, Framework and NuGet Packages

### PR DESCRIPTION
**Pull request by KaiL3**
Update Framework to 4.8.1
Update .netcore 3.1 => .net 8
Update all NuGet Packages
Depend on Update the TestPackage, migrate the Testcode AreEqual => That()

### CODE REVIEW

**Comment by KaiL3** [comment]
Sorry for this confusion, but i would like opening a new Pullrequest from the Development Branch to the Development Branch. In this request are included the .net 8 update from the build project.

**Comment by KaiL3** [comment]
Hi Patrick, I'm surprised. When testing this pull request, it was compiled against .NET 4.7.2. Actually I would have expected .NET 4.8.1 and after the merge the developer pack for the new .NET version was missing. 
Have you also noticed this?

**Comment by Hirogen** [comment]
not really, since target framework is 4.8.1, very strange

**Comment by KaiL3** [comment]
The Developer Pack .NET 4.8.1 must be installed in the pipeline for compilation. Alternatively, a downgrade to .NET Framework 4.8 should also work.
It is interesting that the initial tests did not run on 4.8.1, but on 4.7.2. I tested the build locally, where everything worked. Except for the setup and the package manager, which I did not install locally.

**Pull request merged**
